/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * Jellyfin API
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SessionMessageType } from './session-message-type';

/**
 * Activity log entry start message.  Data is the timing data encoded as \"$initialDelay,$interval\" in ms.
 * @export
 * @interface ActivityLogEntryStartMessage
 */
export interface ActivityLogEntryStartMessage {
    /**
     * Gets or sets the data.
     * @type {string}
     * @memberof ActivityLogEntryStartMessage
     */
    'Data'?: string | null;
    /**
     * 
     * @type {SessionMessageType}
     * @memberof ActivityLogEntryStartMessage
     */
    'MessageType'?: SessionMessageType;
}



