/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * Jellyfin API
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LogLevel } from './log-level';

/**
 * An activity log entry.
 */
export interface ActivityLogEntry {
    /**
     * Gets or sets the identifier.
     */
    'Id'?: number;
    /**
     * Gets or sets the name.
     */
    'Name'?: string;
    /**
     * Gets or sets the overview.
     */
    'Overview'?: string | null;
    /**
     * Gets or sets the short overview.
     */
    'ShortOverview'?: string | null;
    /**
     * Gets or sets the type.
     */
    'Type'?: string;
    /**
     * Gets or sets the item identifier.
     */
    'ItemId'?: string | null;
    /**
     * Gets or sets the date.
     */
    'Date'?: string;
    /**
     * Gets or sets the user identifier.
     */
    'UserId'?: string;
    /**
     * Gets or sets the user primary image tag.
     * @deprecated
     */
    'UserPrimaryImageTag'?: string | null;
    'Severity'?: LogLevel;
}



