/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * Jellyfin API
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */



/**
 * Defines the optional contents of the backup archive.
 */
export interface BackupOptionsDto {
    /**
     * Gets or sets a value indicating whether the archive contains the Metadata contents.
     */
    'Metadata'?: boolean;
    /**
     * Gets or sets a value indicating whether the archive contains the Trickplay contents.
     */
    'Trickplay'?: boolean;
    /**
     * Gets or sets a value indicating whether the archive contains the Subtitle contents.
     */
    'Subtitles'?: boolean;
    /**
     * Gets or sets a value indicating whether the archive contains the Database contents.
     */
    'Database'?: boolean;
}

