/* tslint:disable */
/* eslint-disable */
/**
 * Jellyfin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Client log document response dto.
 * @export
 * @interface ClientLogDocumentResponseDto
 */
export interface ClientLogDocumentResponseDto {
    /**
     * Gets the resulting filename.
     * @type {string}
     * @memberof ClientLogDocumentResponseDto
     */
    FileName?: string;
}


