/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * Jellyfin API
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */



/**
 * A dto representing custom options for a device.
 * @export
 * @interface DeviceOptionsDto
 */
export interface DeviceOptionsDto {
    /**
     * Gets or sets the id.
     * @type {number}
     * @memberof DeviceOptionsDto
     */
    'Id'?: number;
    /**
     * Gets or sets the device id.
     * @type {string}
     * @memberof DeviceOptionsDto
     */
    'DeviceId'?: string | null;
    /**
     * Gets or sets the custom name.
     * @type {string}
     * @memberof DeviceOptionsDto
     */
    'CustomName'?: string | null;
}

