/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * Jellyfin API
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */



/**
 * Enum HardwareEncodingType.
 * @export
 * @enum {string}
 */

export const HardwareEncodingType = {
    Amf: 'AMF',
    Qsv: 'QSV',
    Nvenc: 'NVENC',
    V4L2M2M: 'V4L2M2M',
    Vaapi: 'VAAPI',
    VideoToolBox: 'VideoToolBox',
    Rkmpp: 'RKMPP'
} as const;

export type HardwareEncodingType = typeof HardwareEncodingType[keyof typeof HardwareEncodingType];



