/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * Jellyfin API
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ImageOption } from './image-option';
// May contain unused imports in some cases
// @ts-ignore
import type { ImageType } from './image-type';
// May contain unused imports in some cases
// @ts-ignore
import type { LibraryOptionInfoDto } from './library-option-info-dto';

/**
 * Library type options dto.
 */
export interface LibraryTypeOptionsDto {
    /**
     * Gets or sets the type.
     */
    'Type'?: string | null;
    /**
     * Gets or sets the metadata fetchers.
     */
    'MetadataFetchers'?: Array<LibraryOptionInfoDto>;
    /**
     * Gets or sets the image fetchers.
     */
    'ImageFetchers'?: Array<LibraryOptionInfoDto>;
    /**
     * Gets or sets the supported image types.
     */
    'SupportedImageTypes'?: Array<ImageType>;
    /**
     * Gets or sets the default image options.
     */
    'DefaultImageOptions'?: Array<ImageOption>;
}

