/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * Jellyfin API
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ListingsProviderInfo } from './listings-provider-info';
// May contain unused imports in some cases
// @ts-ignore
import type { TunerHostInfo } from './tuner-host-info';

export interface LiveTvOptions {
    'GuideDays'?: number | null;
    'RecordingPath'?: string | null;
    'MovieRecordingPath'?: string | null;
    'SeriesRecordingPath'?: string | null;
    'EnableRecordingSubfolders'?: boolean;
    'EnableOriginalAudioWithEncodedRecordings'?: boolean;
    'TunerHosts'?: Array<TunerHostInfo> | null;
    'ListingProviders'?: Array<ListingsProviderInfo> | null;
    'PrePaddingSeconds'?: number;
    'PostPaddingSeconds'?: number;
    'MediaLocationsCreated'?: Array<string> | null;
    'RecordingPostProcessor'?: string | null;
    'RecordingPostProcessorArguments'?: string | null;
    'SaveRecordingNFO'?: boolean;
    'SaveRecordingImages'?: boolean;
}

