/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * Jellyfin API
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */



/**
 * 
 * @export
 * @interface PersonLookupInfo
 */
export interface PersonLookupInfo {
    /**
     * Gets or sets the name.
     * @type {string}
     * @memberof PersonLookupInfo
     */
    'Name'?: string | null;
    /**
     * Gets or sets the original title.
     * @type {string}
     * @memberof PersonLookupInfo
     */
    'OriginalTitle'?: string | null;
    /**
     * Gets or sets the path.
     * @type {string}
     * @memberof PersonLookupInfo
     */
    'Path'?: string | null;
    /**
     * Gets or sets the metadata language.
     * @type {string}
     * @memberof PersonLookupInfo
     */
    'MetadataLanguage'?: string | null;
    /**
     * Gets or sets the metadata country code.
     * @type {string}
     * @memberof PersonLookupInfo
     */
    'MetadataCountryCode'?: string | null;
    /**
     * Gets or sets the provider ids.
     * @type {{ [key: string]: string | null; }}
     * @memberof PersonLookupInfo
     */
    'ProviderIds'?: { [key: string]: string | null; } | null;
    /**
     * Gets or sets the year.
     * @type {number}
     * @memberof PersonLookupInfo
     */
    'Year'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PersonLookupInfo
     */
    'IndexNumber'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PersonLookupInfo
     */
    'ParentIndexNumber'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PersonLookupInfo
     */
    'PremiereDate'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PersonLookupInfo
     */
    'IsAutomated'?: boolean;
}

