/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * Jellyfin API
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */



/**
 * The startup configuration DTO.
 * @export
 * @interface StartupConfigurationDto
 */
export interface StartupConfigurationDto {
    /**
     * Gets or sets UI language culture.
     * @type {string}
     * @memberof StartupConfigurationDto
     */
    'UICulture'?: string | null;
    /**
     * Gets or sets the metadata country code.
     * @type {string}
     * @memberof StartupConfigurationDto
     */
    'MetadataCountryCode'?: string | null;
    /**
     * Gets or sets the preferred language for the metadata.
     * @type {string}
     * @memberof StartupConfigurationDto
     */
    'PreferredMetadataLanguage'?: string | null;
}

