/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 *
 * Jellyfin API
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserConfiguration } from './user-configuration';
// May contain unused imports in some cases
// @ts-ignore
import type { UserPolicy } from './user-policy';

/**
 * Class UserDto.
 */
export interface UserDto {
    /**
     * Gets or sets the name.
     */
    'Name'?: string | null;
    /**
     * Gets or sets the server identifier.
     */
    'ServerId'?: string | null;
    /**
     * Gets or sets the name of the server.  This is not used by the server and is for client-side usage only.
     */
    'ServerName'?: string | null;
    /**
     * Gets or sets the id.
     */
    'Id'?: string;
    /**
     * Gets or sets the primary image tag.
     */
    'PrimaryImageTag'?: string | null;
    /**
     * Gets or sets a value indicating whether this instance has password.
     */
    'HasPassword'?: boolean;
    /**
     * Gets or sets a value indicating whether this instance has configured password.
     */
    'HasConfiguredPassword'?: boolean;
    /**
     * Gets or sets a value indicating whether this instance has configured easy password.
     * @deprecated
     */
    'HasConfiguredEasyPassword'?: boolean;
    /**
     * Gets or sets whether async login is enabled or not.
     */
    'EnableAutoLogin'?: boolean | null;
    /**
     * Gets or sets the last login date.
     */
    'LastLoginDate'?: string | null;
    /**
     * Gets or sets the last activity date.
     */
    'LastActivityDate'?: string | null;
    'Configuration'?: UserConfiguration;
    'Policy'?: UserPolicy;
    /**
     * Gets or sets the primary image aspect ratio.
     */
    'PrimaryImageAspectRatio'?: number | null;
}

